@startuml
actor User

participant Component
participant fileTransferring
participant BehaviorSubject

User -> Component: Trigger fileTransfer(file)
Component -> fileTransferring: call fileTransfer(file)
fileTransferring -> dataSource: dataSource.next(file)

User -> Component: Trigger questionTransfer(file)
Component -> fileTransferring: call questionTransfer(file)
fileTransferring -> questionSource: questionSource.next(file)

@enduml
