@startuml
actor User

participant Browser
participant platformBrowserDynamic
participant AppModule
participant console

User -> Browser: Open Application
Browser -> platformBrowserDynamic: Load platformBrowserDynamic
platformBrowserDynamic -> AppModule: bootstrapModule(AppModule, { ngZoneEventCoalescing: true })
alt Successful Bootstrap
    AppModule -> platformBrowserDynamic: return AppModule Instance
    platformBrowserDynamic -> Browser: Application Bootstrapped
else Bootstrap Error
    platformBrowserDynamic -> console: console.error(err)
end

@enduml
