@startuml
actor User

rectangle System {
  User -- (Post Data)
  User -- (Upload File)
  User -- (Upload Question)
  User -- (Upload Python Files)
}

(Post Data) .> (sendToModel) : <<include>>
(sendToModel) .> (get_ai_response) : <<include>>
(get_ai_response) .> (External API) : <<include>>

(Upload File) .> (fileprocessing) : <<include>>
(fileprocessing) .> (saveFile) : <<include>>
(fileprocessing) .> (sendToModel) : <<include>>
(sendToModel) .> (get_ai_response) : <<include>>
(get_ai_response) .> (External API) : <<include>>

(Upload Question) .> (questionprocessing) : <<include>>
(questionprocessing) .> (saveFile) : <<include>>
(questionprocessing) .> (sendToModel) : <<include>>
(sendToModel) .> (get_ai_response) : <<include>>
(get_ai_response) .> (External API) : <<include>>

(Upload Python Files) .> (questionprocessing) : <<include>>
(Upload Python Files) .> (fileprocessing) : <<include>>
(fileprocessing) .> (saveFile) : <<include>>
(questionprocessing) .> (saveFile) : <<include>>
(fileprocessing) .> (sendToModel) : <<include>>
(sendToModel) .> (get_ai_response) : <<include>>
(get_ai_response) .> (External API) : <<include>>
@enduml
